{
	"version": 1551374257,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/background-sheet0.png",
		"images/ground-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/spike-sheet0.png",
		"images/hudbackground-sheet0.png",
		"images/btnhome-sheet0.png",
		"images/btmreplay-sheet0.png",
		"images/btnplay-sheet0.png",
		"images/btnmoregames-sheet0.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coin-sheet2.png",
		"images/gold-sheet0.png",
		"images/gold-sheet1.png",
		"images/gold-sheet2.png",
		"images/clearscreen-sheet0.png",
		"media/hum 3.ogg",
		"media/sound.ogg",
		"media/death.ogg",
		"media/spike a rail.ogg",
		"media/powersot.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}